receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  logging:
      loglevel: debug
      sampling_initial: 5
      sampling_thereafter: 200
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    format: json
    labels:
      resource:
        service.name: "service_name"
        body: ""

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service: 
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [batch]
      exporters: [ prometheus ]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    logs:
      receivers: [ otlp ]
      exporters: [ logging,loki ]